#!/bin/sh
set -e

# --- APP_KEY: explicit env wins, else reuse generated key from /state volume ---
if [ "$SKIP_BOOTSTRAP" = "1" ] && [ -z "$APP_KEY" ]; then
  # Workers share the key generated by `app`: wait for it (max ~60s).
  for i in $(seq 1 30); do
    [ -f /state/app_key ] && break
    sleep 2
  done
fi
if [ -z "$APP_KEY" ] || [ "$APP_KEY" = "base64:YOUR_APP_KEY_HERE" ]; then
  if [ -f /state/app_key ]; then
    APP_KEY="$(cat /state/app_key)"
  else
    APP_KEY="$(php artisan key:generate --show)"
    mkdir -p /state
    printf '%s' "$APP_KEY" > /state/app_key
    echo "Generated APP_KEY (saved in 'state' volume, reused on restarts)."
  fi
  export APP_KEY
fi

# Wait for DB (mariadb needs time on first start)
if [ -n "$DB_HOST" ]; then
  echo "Waiting for DB $DB_HOST:${DB_PORT:-3306}..."
  for i in $(seq 1 60); do
    php -r "try { new PDO('mysql:host=${DB_HOST};port=${DB_PORT:-3306}', getenv('DB_USERNAME'), getenv('DB_PASSWORD')); echo \"ok\n\"; } catch (Throwable \$e) { exit(1); }" && break
    sleep 2
    if [ "$i" = "60" ]; then echo "DB not reachable, continuing anyway"; fi
  done
fi

# Laravel bootstrap (only on main app container, queue worker skips via SKIP_BOOTSTRAP=1)
if [ "$SKIP_BOOTSTRAP" != "1" ]; then
  php artisan storage:link 2>/dev/null || true
  php artisan migrate --force
  # Idempotent (insertIfNotExists): root album, admin/admin123, ratings, reactions
  php artisan db:seed --force
  php artisan config:cache
  php artisan route:cache
  php artisan view:cache
  chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true
  # Repair dirs created 0700 by Flysystem default (nginx needs +x for X-Accel-Redirect)
  chmod -R a+rX storage/app/thumbs storage/app/og storage/app/users 2>/dev/null || true
  # Signal that migrations are done for scheduler/workers
  mkdir -p /state
  printf '%s' 'done' > /state/migrations_done
fi

# Scheduler: run initial indexing once at startup, then continue to schedule:work
# CMD is ["php", "artisan", "schedule:work"], so $3 == "schedule:work"
if [ "$SKIP_BOOTSTRAP" = "1" ] && [ "$3" = "schedule:work" ]; then
  # Wait for app to finish migrations (marker in shared state volume)
  echo "Waiting for migrations to complete..."
  for i in $(seq 1 60); do
    [ -f /state/migrations_done ] && break
    sleep 2
    if [ "$i" = "60" ]; then echo "Migrations marker not found, continuing anyway"; fi
  done
  echo "Running initial media indexing..."
  php artisan app:index --layers --missing=skip 2>/dev/null || true
  chmod -R a+rX storage/app/thumbs storage/app/og storage/app/users 2>/dev/null || true
fi

exec "$@"
